import { useState } from 'react'
import { MetaTags } from '../../components/MetaTags'
import { ToolLayout } from '../../components/ToolLayout'
import { FAQSection } from '../../components/FAQSchema'
import { htmlToPDF, downloadBlob } from '../../lib/pdfEngine'
import { Download } from 'lucide-react'

type ToolState = 'idle' | 'processing' | 'success' | 'error'

const sampleHTML = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #1e3a8a; }
    p { line-height: 1.6; }
  </style>
</head>
<body>
  <h1>My Document Title</h1>
  <p>This is a paragraph with <strong>bold</strong> and <em>italic</em> text.</p>
  <ul>
    <li>Item one</li>
    <li>Item two</li>
  </ul>
</body>
</html>`

const faqs = [
  {
    question: 'Can I use external CSS in my HTML?',
    answer: 'External CSS files loaded via URL (e.g., Google Fonts, CDN stylesheets) should work if our server can reach them. Inline CSS and <style> blocks are the most reliable approach for consistent rendering.',
  },
  {
    question: 'Are external images supported?',
    answer: 'Images referenced via URLs in <img> tags will be fetched and included in the PDF if they are publicly accessible. Data URIs (base64-encoded images) also work reliably.',
  },
  {
    question: 'Will JavaScript in my HTML be executed?',
    answer: 'The PDF converter may execute basic JavaScript, but complex JavaScript-dependent content (dynamically generated by frameworks like React) is not guaranteed to render correctly. For best results, provide the final rendered HTML rather than template code.',
  },
  {
    question: 'What page size is used for the PDF?',
    answer: 'By default, A4 page size is used. You can influence page breaks in your HTML by using CSS page-break properties: page-break-before, page-break-after, and page-break-inside.',
  },
  {
    question: 'Is there an HTML size limit?',
    answer: 'The HTML input should be under 5 MB for reliable processing. Very long or complex HTML with many large images may take longer to process.',
  },
]

export default function HTMLToPDF() {
  const [html, setHtml] = useState('')
  const [state, setState] = useState<ToolState>('idle')
  const [error, setError] = useState('')
  const [resultBlob, setResultBlob] = useState<Blob | null>(null)

  const handleConvert = async () => {
    if (!html.trim()) return
    setState('processing')
    try {
      const blob = await htmlToPDF(html)
      setResultBlob(blob)
      setState('success')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to convert HTML to PDF')
      setState('error')
    }
  }

  const handleDownload = () => {
    if (resultBlob) downloadBlob(resultBlob, 'document.pdf')
  }

  const handleReset = () => {
    setState('idle')
    setResultBlob(null)
    setError('')
  }

  return (
    <>
      <MetaTags
        title="HTML to PDF | Convert HTML to PDF Free | EasyPDFKit"
        description="Convert HTML code to a PDF document online for free. Supports inline CSS, images, and formatting. No signup required."
        canonical="https://easypdfkit.org/html-to-pdf"
      />
      <ToolLayout
        title="HTML to PDF"
        description="Convert HTML code into a formatted PDF document. Supports inline CSS styles, tables, images, and standard HTML elements."
        breadcrumb="Utilities"
        breadcrumbHref="/html-to-pdf"
        state={state}
        errorMessage={error}
        successContent={
          <div>
            <p className="text-gray-600 mb-6">Your HTML has been converted to a PDF document.</p>
            <div className="flex flex-wrap gap-3 justify-center">
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors"
              >
                <Download size={18} />
                Download PDF
              </button>
              <button onClick={handleReset} className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition-colors">
                Convert More HTML
              </button>
            </div>
          </div>
        }
      >
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium text-gray-700">HTML Content</label>
            <button
              onClick={() => setHtml(sampleHTML)}
              className="text-sm text-blue-600 hover:text-blue-700"
            >
              Load example
            </button>
          </div>
          <textarea
            value={html}
            onChange={e => setHtml(e.target.value)}
            placeholder="Paste your HTML code here…"
            rows={16}
            className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm resize-y"
          />
          <button
            onClick={handleConvert}
            disabled={!html.trim()}
            className="w-full py-3.5 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Convert to PDF
          </button>
        </div>
      </ToolLayout>

      <div className="max-w-3xl mx-auto px-4 pb-16">
        <div className="prose max-w-none">
          <h2>Converting HTML to PDF</h2>
          <p>
            HTML to PDF conversion is widely used for generating dynamic documents from web content. Use cases include generating invoices, reports, certificates, and printable versions of web pages. Our converter processes your HTML using a headless browser rendering engine, which means it interprets HTML and CSS just like a real browser would.
          </p>
          <h2>Tips for Best Results</h2>
          <ul>
            <li>Use inline CSS or a <code>&lt;style&gt;</code> block for the most reliable styling</li>
            <li>Set appropriate page margins using CSS: <code>@page {'{'} margin: 20mm; {'}'}</code></li>
            <li>Control page breaks with <code>page-break-before: always</code> on elements that should start on a new page</li>
            <li>Test with complete HTML including <code>&lt;!DOCTYPE html&gt;</code> and proper structure</li>
            <li>Use standard web fonts or embed fonts as base64 for consistent typography</li>
          </ul>
          <h2>Common HTML to PDF Use Cases</h2>
          <ul>
            <li><strong>Invoices and receipts:</strong> Generate PDF invoices from HTML templates</li>
            <li><strong>Reports:</strong> Convert data-driven HTML reports to shareable PDFs</li>
            <li><strong>Certificates:</strong> Create styled certificates or awards as PDFs</li>
            <li><strong>Web page snapshots:</strong> Capture a static version of a web page as PDF</li>
            <li><strong>Email templates:</strong> Preview and save HTML email templates as PDF</li>
          </ul>
          <h2>Related Tools</h2>
          <ul>
            <li><a href="/text-to-pdf" className="text-blue-600">Text to PDF</a> — Convert plain text to PDF</li>
            <li><a href="/word-to-pdf" className="text-blue-600">Word to PDF</a> — Convert Word documents to PDF</li>
            <li><a href="/compress-pdf" className="text-blue-600">Compress PDF</a> — Reduce the resulting PDF file size</li>
          </ul>
        </div>
        <FAQSection faqs={faqs} />
      </div>
    </>
  )
}
